name 'cookbook-qubell-selenium'
maintainer 'Cameron Johnston, Dmytro Makhno, Vasyl Khomenko, Artem Ivantsov, Anton Butovich'
maintainer_email 'support@qubell.com'
description 'installs components required for running selected flavors of selenium and selenium grid'
version '2.0.0'

depends 'selenium', '= 2.8.1'
depends 'chrome', '~> 1.0.9'
depends 'yum', '~> 3.2'
depends 'firefox', '>= 2.0.0'
depends 'java', '~> 1.31.0'
depends 'windows', '= 1.38.1'
depends 'nssm', '~> 1.0'
depends 'ie', '~> 2.1.1'
